### ISSUE TITLE
Verify this works for 5.6.3

### ISSUE THREAD

**Issue by mkly** [mkly/concrete5-Lockpick#3]
I think this should still work with 5.6.3

Just in case I'm leaving this here to remind myself.

**Comment by mnakalay** [comment]
Hello, I just wanted to let you know that this works perfectly with the 5.7 branch. I was able to modify admin password without a problem.

**Comment by mkly** [comment]
I can't believe I missed this message. I'll open a new one to check on 8. Thanks!
