### ISSUE TITLE
Get working on version 8

### ISSUE THREAD

**Issue by mkly** [mkly/concrete5-Lockpick#4]
This works up until version 5.7. Install, test and then fix for 8.

**Comment by mnakalay** [comment]
I ran some tests and one line was changed in the dispatcher in v8. The line
`if ($response = $runtime->run()) {`
used to be
`if (!$cms->isRunThroughCommandLineInterface()) {`
Replacing the new if with the old one makes LockPick work again.
Keeping the new one, nothing happens, the if is not resolved one way or another so I think it gets stuck somewhere running the run() function on $runtime.

**Comment by mnakalay** [comment]
Here's the exact error
in file concrete\vendor\symfony\console\Input\ArgvInput.php on line 59 

array_shift() expects parameter 1 to be array, null given

**Comment by jasteele12** [comment]
So, a few years later and much work done on the CLI side, any chance of a fix?

**Comment by mnakalay** [comment]
I went ahead and created a new tool that does the same but takes into account more scenarios like of the admin account was deleted for instance. You can find it here https://github.com/mnakalay/Concrete5-Super-User-recovery

**Comment by mkly** [comment]
@mnakalay That's great to hear. I'll update the readme to direct people to the tool you created. :tropical_drink:

**Comment by mnakalay** [comment]
thank you :)
